### ISSUE TITLE
BATCH PROCESS REQUEST: saving batch process into one text file, line for line 

### ISSUE THREAD

**Issue by demirklvc** [pharmapsychotic/clip-interrogator-ext#12]
BATCH PROCESS REQUEST: saving batch process into one text file, line for line

So it can be used for batch generation (using textfile to img script)

Please :)

**Comment by pharmapsychotic** [comment]
Wish granted! Update the extension and version 0.0.7 has 3 output modes to pick from including "Single text file with all prompts"
