### ISSUE TITLE
The size of tensor a (8) must match the size of tensor b (64) at non-singleton dimension 0

### ISSUE THREAD

**Issue by VictorGalu** [pharmapsychotic/clip-interrogator-ext#21]
Hello! I can't start interogator-ext. Running on the "Promt" tab interrupts with "Exception <class 'RuntimeError'>". In the terminal the error "The size of tensor a (8) must match the size of tensor b (64) at non-singleton dimension", Tab "Analyze" and "Internal CLIP" and "DeepBooru" work. Can anyone help me with this problem?

**Comment by adisakau** [comment]
I have the same issue. If anyone found a solution, please kindly share.

**Comment by sergiobr** [comment]
I have the same here. Also happens with SmartPreprocess extension. It's working with img2img tab's button Clip Interrogator.

**Comment by Vigilence** [comment]
Same issue.

**Comment by VictorGalu** [comment]
Hi< we found solution: https://github.com/pharmapsychotic/clip-interrogator/pull/63

**Comment by Vigilence** [comment]
How do I implement the solution?

Manually installed transformers 4.26.1 doesn't fix the issue on my end.

**Comment by pharmapsychotic** [comment]
If you have another extension installed like Dreambooth which is pinning 4.27 then each time you run auto1111 it may install the newer transformers which breaks CLIP Interrogator. Working on update now so that transformers 4.27 can be supported.

**Comment by Vigilence** [comment]
> If you have another extension installed like Dreambooth which is pinning 4.27 then each time you run auto1111 it may install the newer transformers which breaks CLIP Interrogator. Working on update now so that transformers 4.27 can be supported.

That's exactly the issue I have.  Thank you for looking into a fix.  ❤

**Comment by pharmapsychotic** [comment]
@Vigilence can you give it a try now? After updating extension you will need full restart of the webui.

**Comment by Vigilence** [comment]
> @Vigilence can you give it a try now? After updating extension you will need full restart of the webui.

Working great, thank you!

**Comment by pharmapsychotic** [comment]
okay that's good news!
