### ISSUE TITLE
incorrect memory check

### ISSUE THREAD

**Issue by vladmandic** [pharmapsychotic/clip-interrogator-ext#26]
latest version adds checks for available vram in `scripts/clip_interrogator_ext.py`, but it does so incorrectly.

```
def add_tab():
    global low_vram
    low_vram = shared.cmd_opts.lowvram or shared.cmd_opts.medvram
    if not low_vram and torch.cuda.is_available():
        device = devices.get_optimal_device()
        vram_total = torch.cuda.get_device_properties(device).total_memory
        if vram_total < 12*1024*1024*1024:
            low_vram = True
            print(f"    detected < 12GB VRAM, using low VRAM mode")
```

first, 12GB GPUs always report as slightly less. so this check would only pass for 16GB GPUs since that is the first valid one after 12GB.
for example, RTX3060 reports `12884377600` which is **11.8 GB**.

second, if check does not pass, message printed to console is without any context whatsover.
its indented (and no other console messages are) and there is no mention it comes from clip interrogator extension.
how is user to know what does this refer to?

**Comment by pharmapsychotic** [comment]
Thank! I've moved the info that low VRAM config is being used now to the About tab and changed the threshold so it should pick up 12GB GPUs as regular now.
