### ISSUE TITLE
No indicator that batch process runs

### ISSUE THREAD

**Issue by MeinDeutschkurs** [pharmapsychotic/clip-interrogator-ext#51]
Hi again,
I noticed that after pressing the button, there is no indicator / information that the process started (or failed).

Greetings from Austria,
Johannes

**Comment by pharmapsychotic** [comment]
Sorry yeah the webui doesn't display the status but if you hop back over to the command line where you launch the webui you should see progress bar and status there.

**Comment by MeinDeutschkurs** [comment]
Yes, it shows. Most of the time, I cannot see the terminal. But no problem. Now I know that there is no inficator.
