### ISSUE TITLE
[Feature Request] : Ext through API

### ISSUE THREAD

**Issue by MeinDeutschkurs** [pharmapsychotic/clip-interrogator-ext#52]
Hi everyone,
I'm stuck I cannot figure out, how to submit the model "fast" instead of the default one:

<img width="1249" alt="Bildschirmfoto 2023-06-03 um 18 08 43" src="https://github.com/pharmapsychotic/clip-interrogator-ext/assets/129950466/d2ab7dbc-361a-4bbc-9e3b-bf45e70301f0">
Has this feature not been implemented yet, or am I overlooking something?

Greetings from Austria,
Johannes

**Comment by MeinDeutschkurs** [comment]
I want to specify this: With "what I want" I mean: clip model "fast" instead of the default one, that is used.

**Comment by pharmapsychotic** [comment]
Oh that API is using the version of CLIP Interrogator that is builtin to stable-diffusion-webui and doesn't have all the modes of the extension. You can use the CLIP Interrogator library directly from https://github.com/pharmapsychotic/clip-interrogator if you are writing scripts and want to generate prompts.

**Comment by MeinDeutschkurs** [comment]
For real? At the GUI I can select „fast“ and it works great. I can write „CLIP“ at the API, but I cannot select the mode, which is available threw checkbox at the GUI.

I see, the API endpoint has nothing to do with your extension. If so, sorry for the mix up. So, I should use the command line version.

I will loose the queue, but I‘ll try it. Thx.

**Comment by MeinDeutschkurs** [comment]
@pharmapsychotic , according to https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11190#issuecomment-1588636208 I'd suggest to make your extension available through API. That would be fantastic.

**Comment by pharmapsychotic** [comment]
ooh that's cool, didn't know you could do that!

**Comment by cpietsch** [comment]
Hey @MeinDeutschkurs, are you making progress on the the API integration ? I am thinking of doing the same.

**Comment by MeinDeutschkurs** [comment]
> Hey @MeinDeutschkurs, are you making progress on the the API integration ? I am thinking of doing the same.

I was asking for doing this. I'm not a programmer, I'm keen to test and play.

**Comment by MeinDeutschkurs** [comment]
> Hey @MeinDeutschkurs, are you making progress on the the API integration ? I am thinking of doing the same.

I watched yesterday some videos about FastAPI and grado. It‘s amazing, how Interfaces and endpoints can be knitted with it. At the weekend I try to combine all my local models with it. 

As mentioned, I love the queue system. Who knows, maybe I‘m then able to understand the above code. I don‘t want to exclude it. But first I have to understand all of this.

**Comment by MeinDeutschkurs** [comment]
> Working on it and will make a pull request soon. Is there a rule/convention for naming an extension api endpoint ?
> 
> For now I went with `/interrogator/models` and `/interrogator/analyze`

That is amazing! Thank you so much for your efforts!!! At the weekend I was able to get in touch with python and FastAPI. I came not that far, I'm scratching on the very top of the ice-plate. I have no idea about conventions, but maybe /interrogator-ext/models ... /interrogator-ext/analyse makes sense, to avoid mismatch with the stock-one.

**Comment by cpietsch** [comment]
I went for the /interrogator/* path since the internal one is exposed via /sdapi/v1/interrogate

**Comment by MeinDeutschkurs** [comment]
Thank you so much! That's awesome! I did the update through webui and I can't wait to test it later that day! 👏👏👏👏
