### ISSUE TITLE
How can I get VIL-L-14 model, always error

### ISSUE THREAD

**Issue by DuroCuri** [pharmapsychotic/clip-interrogator-ext#55]
As I use clip extension, my internet is bad, I can not get this model. Please, can you tell me where may I download this model to set it into.

**Comment by pharmapsychotic** [comment]
under the models folder create the `clip-interrogator` subfolder then you can download the ViT-L-14 preprocessed files from https://huggingface.co/pharma/ci-preprocess/tree/main and place them there. 
hope this helps!
