### ISSUE TITLE
Works awesome-is batch interrogation possible?

### ISSUE THREAD

**Issue by demirklvc** [pharmapsychotic/clip-interrogator-ext#8]
Works awesome-is batch interrogation possible?

**Comment by demirklvc** [comment]
?

**Comment by pharmapsychotic** [comment]
Yes it's been popular request on twitter for the extension as well and I started a new Batch tab for it the other night. shouldn't take to long to finish up

**Comment by demirklvc** [comment]
thanks. your work is appreciated.

**Comment by pharmapsychotic** [comment]
Update the extension to latest version and there is Batch tab now. It saves to .txt with same name as image file, I believe this is the most popular format now yeah?

**Comment by Dragoy** [comment]
> Update the extension to latest version and there is Batch tab now. It saves to .txt with same name as image file, I believe this is the most popular format now yeah?

Cool, thanks for the promptness. Yes, at least this workflow is suitable for kohya_ss.

**Comment by Dragoy** [comment]
sometimes does not always want to describe the files when selecting batch. The console writes this:
<img width="633" alt="image" src="https://user-images.githubusercontent.com/4968313/223197577-578d4e45-5c1c-4a6a-854c-561d6a1e31d8.png">

**Comment by pharmapsychotic** [comment]
Sorry it was choking on images with alpha channel. This is now fixed if you check for and install the extension update.
