### ISSUE TITLE
Prompt text field doesn't expand.

### ISSUE THREAD

**Issue by Nacurutu** [pharmapsychotic/clip-interrogator-ext#9]
I dnt know if it just me, or it happens to everyone, however, the Prompt text field doesn't expand.

![image](https://user-images.githubusercontent.com/18109442/221310411-10c0e8f8-5d1d-4918-bf4b-462c75911555.png)

**Comment by pharmapsychotic** [comment]
thanks, I'll expand it to multiple lines

**Comment by pharmapsychotic** [comment]
@Nacurutu if you update it is 3 lines now 👍
